### ISSUE TITLE
Keep WEKA model in memory

### ISSUE THREAD

**Issue by sjcross** [mianalysis/mia#110]
Have option to keep model in memory.  This would save it needing to be loaded multiple times.

Would have to store the full WekaSegmentation object.  If object storing is enabled, it would check if a static instance exists.  If it doesn't then it would load it. 

If the classifier file path parameter was changed, the model would need to be removed.

**Comment by alibhaid** [comment]
Good idea

**Comment by sjcross** [comment]
Added for v1.6.3
