### ISSUE TITLE
Consider deploying via update site

### ISSUE THREAD

**Issue by imagejan** [mianalysis/mia#141]
See [this forum topic](https://forum.image.sc/t/requests-for-creating-imagej-update-sites/40051?u=imagejan) for how to request an update site currently.

**Comment by sjcross** [comment]
Thanks for the suggestion, will get onto setting this up!

**Comment by sjcross** [comment]
Now all set up via https://sites.imagej.net/ModularImageAnalysis/.  Thanks again for the suggestion!
