### ISSUE TITLE
"refresh test file" not available anymore in input control

### ISSUE THREAD

**Issue by Rcolenbier** [mianalysis/mia#184]
In previous versions, there used to be a "refresh test file" option under the "core import controls" (if I remember correctly) to quickly switch between test images loaded into the pipeline. However, in the latest version this appears to have disappeared? I am not an expert in coding by any means so please let me know if there is an easy fix for this issue.

Thanks!

**Comment by sjcross** [comment]
Hi, you do remember correctly, there did indeed use to be this button.  With the latest update (v1.5.0), MIA should recognise when you change the input path and automatically switch the test file it's using.  

At the moment, it's just "Input path" that can do this; however, in the next release (hopefully out in the next couple of days), any parameter changes in the "Input control" module (e.g. changing the series or adding/removing file filters) will trigger working with a new test file.

Please let me know if changing the "Input path" isn't changing the test file as expected.

Cheers,
Stephen

**Comment by Rcolenbier** [comment]
Dear Stephen

thanks for the reply, and apologies for my late one!

Indeed, it goes automatically now!

Kind regards

**Comment by sjcross** [comment]
No worries, thanks for letting me know :)
