### ISSUE TITLE
Convert Parameter and Measurement interfaces to enum

### ISSUE THREAD

**Issue by sjcross** [mianalysis/mia#70]

**Comment by SJCross** [comment]
Will likely need to include patterns to identify bits for replacement.  The existing ${} wont' work, as {} are restricted.  Could use $$VALUE$$ instead.  Could also use underscores as an identifier for sentence structure.

ChoiceArray Parameter types (in new inherited Parameter model) would need to take the enums as an argument, so they may need to implement a specific interface:

interface BaseEnum { }
    
enum Meas implements BaseEnum {
        TEST1,TEST2;
}
    
class NewParameter {        
        public NewParameter(BaseEnum baseEnum, BaseEnum[] all) {
                
        }
}

**Comment by sjcross** [comment]
Actually, interfaces are working fine and this would cause compatibility issues
