### ISSUE TITLE
Texture measurement with local radius

### ISSUE THREAD

**Issue by alibhaid** [mianalysis/mia#99]
Tried using this - doesn't work - just calls me a nan - i'm not a nan, i'm a man - i'm going back to cell profiler

**Comment by sjcross** [comment]
Just working through old bugs (also 😅 at the bug report!).  

This one shouldn't be an issue any more as I removed the option to use local radii.  The "new" method would be to generate a local region for each object (https://mianalysis.github.io/mia/html/modules/objects/process/getlocalobjectregion.html), then calculate the texture of that.
